# markdownlint — Configuration
# Réf. : https://github.com/DavidAnson/markdownlint
MD013:
  line_length: 500
MD033:
  allowed_elements:
    - div
    - br
    - img
    - sup
    - sub
    - details
    - summary
MD041: false
MD024:
  siblings_only: true
MD036: false
MD028: false
MD029: false
MD040: false
MD046:
  style: fenced
MD060: false
