---
# yamllint — Configuration
# Réf. : https://yamllint.readthedocs.io/
extends: default

rules:
  line-length:
    max: 200
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  truthy:
    allowed-values: ["true", "false", "yes", "no"]
    check-keys: false
  comments:
    min-spaces-from-content: 1
  comments-indentation: false
  document-start:
    present: true
  indentation:
    spaces: 2
    indent-sequences: true
  braces:
    max-spaces-inside: 1
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true

ignore:
  - .git/
  - node_modules/
  - .terraform/
