---
name: 🐛 Rapport de bug
description: Signaler un bug ou une incohérence dans la documentation ou les scripts.
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Merci de signaler ce bug ! Veuillez remplir les sections ci-dessous.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Description claire du bug.
      placeholder: "L'IP de rp-prod01 est incohérente entre..."
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Localisation
      description: "Chemin du fichier et section où se trouve le bug."
      placeholder: "runbooks/RUNBOOK-DEPLOIEMENT-ARCHI-EN-1-JOUR.md §4.8"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportement attendu
      description: Que devrait-il se passer ?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportement constaté
      description: Que se passe-t-il actuellement ?
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Catégorie
      options:
        - Documentation
        - Runbook
        - Playbook Ansible
        - Script PowerShell
        - Modèle de configuration
        - CI/CD
        - Autre
    validations:
      required: true
